"""add fkey contraint of scholarship_match

Revision ID: a6fc134f67cf
Revises: ae306d25643d
Create Date: 2025-05-12 22:24:34.640526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6fc134f67cf'
down_revision: Union[str, None] = 'ae306d25643d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship_matchs', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('scholarship_matchs', sa.Column('scholarship_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'scholarship_matchs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'scholarship_matchs', 'scholarships', ['scholarship_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scholarship_matchs', type_='foreignkey')
    op.drop_constraint(None, 'scholarship_matchs', type_='foreignkey')
    op.drop_column('scholarship_matchs', 'scholarship_id')
    op.drop_column('scholarship_matchs', 'user_id')
    # ### end Alembic commands ###
