"""remove fkey contraint of scholarship_match

Revision ID: bf2ad774f4de
Revises: 3e904e4b57f8
Create Date: 2025-05-12 22:23:30.177269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2ad774f4de'
down_revision: Union[str, None] = '3e904e4b57f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scholarship_matchs_scholarship_id_fkey', 'scholarship_matchs', type_='foreignkey')
    op.drop_constraint('scholarship_matchs_user_id_fkey', 'scholarship_matchs', type_='foreignkey')
    op.drop_column('scholarship_matchs', 'user_id')
    op.drop_column('scholarship_matchs', 'scholarship_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship_matchs', sa.Column('scholarship_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('scholarship_matchs', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('scholarship_matchs_user_id_fkey', 'scholarship_matchs', 'users', ['user_id'], ['id'])
    op.create_foreign_key('scholarship_matchs_scholarship_id_fkey', 'scholarship_matchs', 'scholarship', ['scholarship_id'], ['id'])
    # ### end Alembic commands ###
